services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pizzadatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=-ppassword'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'
    networks:
      pizzaservice:

networks:
  pizzaservice: