apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: pizza-customer
  labels:
    app: pizza-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-customer
  template:
    metadata:
      name: pizza-customer
      labels:
        app: pizza-customer
    spec:
      containers:
        - name: pizza-customer
          image: diegoj4v/pizza-customer:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /customer/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              port: 80
              path: /customer/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 30
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_USERNAME
              value: default_user_A0aXhobZmUUPpyhSVoH
            - name: SPRING_RABBITMQ_PASSWORD
              value: YFARyA7v-OY5SdCjOi5fN3CtfQ2zKukw
            - name: COOKIE_SECURE
              value: "true"
            - name: COOKIE_DOMAIN
              value: localhost
            - name: COOKIE_SAME-SITE
              value: Strict
            - name: MYSQL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_domain
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: JWT_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: jwt_domain

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-customer-svc
spec:
  selector:
    app: pizza-customer
  ports:
    - port: 80
      targetPort: 80