apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-order
  labels:
    app: pizza-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-order
  template:
    metadata:
      name: pizza-order
      labels:
        app: pizza-order
    spec:
      containers:
        - name: pizza-order
          image: diegoj4v/pizza-order:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 80
              path: /order/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              port: 80
              path: /order/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 30
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_domain
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql_password
            - name: JWT_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: jwt_domain
            - name: CUSTOMER_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: customer_domain
            - name: INGREDIENT_SERVICE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: ingredient_domain

---
apiVersion: v1
kind: Service
metadata:
  name: pizza-order-svc
spec:
  selector:
    app: pizza-order
  ports:
    - port: 80
      targetPort: 80
