apiVersion: v1
kind: Service
metadata:
  name: mysql-data-svc
spec:
  selector:
    app: mysql-data
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-data
  labels:
    app: mysql-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-data
  template:
    metadata:
      name: mysql-data
      labels:
        app: mysql-data
    spec:
      containers:
        - name: mysql-data
          image: mysql:8.2.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: -ppassword
            - name: MYSQL_DATABASE
              value: pizzadatabase
            - name: MYSQL_USER
              value: myuser
            - name: MYSQL_PASSWORD
              value: secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data-persistent-storage
              mountPath: /var/lib/mysql-data
      volumes:
        - name: mysql-data-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-data-pv-claim
      restartPolicy: Always

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi



