name: Test frontend workflow

on:
   push:
      paths: [frontend/**, .github/workflows/frontend_workflow.yml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   test:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: frontend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: frontend
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 18
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: Test project
           run: npm run test
   
   e2e-cypress:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: frontend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: frontend
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 18
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: Initialize e2e tests
           run: npm run dev & npm run cy:ci-cd