name: Test frontend workflow

on:
   push:
      paths: [frontend/**, .github/workflows/frontend_workflow.yml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
   test:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: frontend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: frontend
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: Test project
           run: npm run test
   
   e2e-cypress:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: frontend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: frontend
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: create env file
           run: |
            touch .env
            echo PUBLIC_URL=${{ secrets.PUBLIC_URL }} >> .env
         - name: Build application
           run: npm run build
         - name: Initialize e2e tests
           run: npm run preview & npm run cy:ci-cd

   build__and__deploy:
      needs: [test, e2e-cypress]
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: frontend
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: frontend
            fetch-depth: 0
         - uses: actions/setup-node@v4
           with:
            node-version: 20
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
         - name: Install dependencies
           run: npm ci
         - name: Build application
           run: npm run build           
           env: 
            PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
            PRIVATE_URL: ${{ secrets.PRIVATE_URL }}
         - name: Build image
           run: docker build -t diegoj4v/pizza-client .
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
            username: diegoj4v
            password: ${{ secrets.DOCKERHUB_TOKEN }}
         - name: Push image to docker hub
           run: docker push diegoj4v/pizza-client:latest