name: Publish pizza order image

on:
   push:
      paths: [backend/pizza-order/**, .github/workflows/pizza_order_workflow.yaml, '!**.md', '!**.MD']
      branches:
         - main 

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

permissions:
   id-token: write

env:
   PROJECT_ID: ${{ secrets.PROJECT_ID }}
   PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}

   CLUSTER: pizza-cluster
   CLUSTER_ZONE: us-west1-a

jobs:
   test__and__build__image:
      runs-on: ubuntu-22.04
      defaults:
         run:
            working-directory: backend/pizza-order
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: backend/pizza-order
            fetch-depth: 0
         - uses: actions/setup-java@v4
           with:
            distribution: 'temurin'
            java-version: '21'
         - name: Test and publish image
           run: ./mvnw spring-boot:build-image -Ddocker-password=${{ secrets.DOCKERHUB_TOKEN }} -Dgit-hash=$(git rev-parse --short ${{ github.sha }})

   login__and__update__deployment: 
      needs: [test__and__build__image]
      runs-on: ubuntu-22.04
      permissions:
         id-token: write
         contents: read
      defaults:
         run:
            working-directory: k8s
      steps:
         - uses: actions/checkout@v4
           with:
            sparse-checkout: k8s
            fetch-depth: 0
         - id: 'auth'
           name: 'Obtain access token by using workload identity federation'
           uses: 'google-github-actions/auth@v2'
           with:
            workload_identity_provider: ${{ secrets.WIP }}
            service_account: ${{ secrets.SERVICE_EMAIL }}
         - name: Connect to GKE
           uses: google-github-actions/get-gke-credentials@v2
           with:
            cluster_name: pizza-cluster
            location: us-west2
         - name: Update deployment image
           run: kubectl set image deployment/pizza-order pizza-order=diegoj4v/pizza-order:$(git rev-parse --short ${{ github.sha }})